// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SubGD_single_hinge
Rcpp::List SubGD_single_hinge(arma::mat& X, arma::vec& y, arma::mat& b_init, int T, double a_lambda, double b_lambda, double lambda, double eps, bool quiet);
RcppExport SEXP _dcensvm_SubGD_single_hinge(SEXP XSEXP, SEXP ySEXP, SEXP b_initSEXP, SEXP TSEXP, SEXP a_lambdaSEXP, SEXP b_lambdaSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a_lambda(a_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type b_lambda(b_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(SubGD_single_hinge(X, y, b_init, T, a_lambda, b_lambda, lambda, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// SubGD_hinge
Rcpp::List SubGD_hinge(arma::mat& X, arma::vec& y, arma::vec& b_init, int T, double a_lambda, double b_lambda, int nlambda, double lambda_factor, double lambda_max, double eps, bool quiet);
RcppExport SEXP _dcensvm_SubGD_hinge(SEXP XSEXP, SEXP ySEXP, SEXP b_initSEXP, SEXP TSEXP, SEXP a_lambdaSEXP, SEXP b_lambdaSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a_lambda(a_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type b_lambda(b_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(SubGD_hinge(X, y, b_init, T, a_lambda, b_lambda, nlambda, lambda_factor, lambda_max, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_single_svm
Rcpp::List deSubGD_single_svm(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, int T, double a, double b, double lambda, double eps, bool quiet);
RcppExport SEXP _dcensvm_deSubGD_single_svm(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_single_svm(X, y, adjacency_matrix, B_init, T, a, b, lambda, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_svm
Rcpp::List deSubGD_svm(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, int T, double a, double b, int nlambda, double lambda_factor, double lambda_max, double eps, bool quiet);
RcppExport SEXP _dcensvm_deSubGD_svm(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_svm(X, y, adjacency_matrix, B_init, T, a, b, nlambda, lambda_factor, lambda_max, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_single_svm_real
Rcpp::List deSubGD_single_svm_real(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& divisions, int T, double a, double b, double lambda, double eps, bool quiet);
RcppExport SEXP _dcensvm_deSubGD_single_svm_real(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP divisionsSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type divisions(divisionsSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_single_svm_real(X, y, adjacency_matrix, B_init, divisions, T, a, b, lambda, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_svm_real
Rcpp::List deSubGD_svm_real(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& divisions, int T, double a, double b, int nlambda, double lambda_factor, double lambda_max, double eps, bool quiet);
RcppExport SEXP _dcensvm_deSubGD_svm_real(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP divisionsSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type divisions(divisionsSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_svm_real(X, y, adjacency_matrix, B_init, divisions, T, a, b, nlambda, lambda_factor, lambda_max, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// Phi
double Phi(double x);
RcppExport SEXP _dcensvm_Phi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Phi(x));
    return rcpp_result_gen;
END_RCPP
}
// calL_h_G_prime
double calL_h_G_prime(double v, double h);
RcppExport SEXP _dcensvm_calL_h_G_prime(SEXP vSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(calL_h_G_prime(v, h));
    return rcpp_result_gen;
END_RCPP
}
// calL_h_G_double_prime
double calL_h_G_double_prime(double v, double h);
RcppExport SEXP _dcensvm_calL_h_G_double_prime(SEXP vSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(calL_h_G_double_prime(v, h));
    return rcpp_result_gen;
END_RCPP
}
// grad_hinge_loss
arma::vec grad_hinge_loss(arma::vec& Y, arma::mat& X, arma::vec& beta, double h, int type);
RcppExport SEXP _dcensvm_grad_hinge_loss(SEXP YSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP hSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_hinge_loss(Y, X, beta, h, type));
    return rcpp_result_gen;
END_RCPP
}
// L2_HingeLoss
double L2_HingeLoss(double v, double h, int type);
RcppExport SEXP _dcensvm_L2_HingeLoss(SEXP vSEXP, SEXP hSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(L2_HingeLoss(v, h, type));
    return rcpp_result_gen;
END_RCPP
}
// calculateAccuracy
double calculateAccuracy(arma::vec& y, arma::vec& y_pred);
RcppExport SEXP _dcensvm_calculateAccuracy(SEXP ySEXP, SEXP y_predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y_pred(y_predSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateAccuracy(y, y_pred));
    return rcpp_result_gen;
END_RCPP
}
// getSampleIndices
arma::uvec getSampleIndices(const arma::vec& divisions, int division);
RcppExport SEXP _dcensvm_getSampleIndices(SEXP divisionsSEXP, SEXP divisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type divisions(divisionsSEXP);
    Rcpp::traits::input_parameter< int >::type division(divisionSEXP);
    rcpp_result_gen = Rcpp::wrap(getSampleIndices(divisions, division));
    return rcpp_result_gen;
END_RCPP
}
// decentralizedsvm_cpp
Rcpp::List decentralizedsvm_cpp(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec betaT, double h, int type, double C_N, int T_outer, double c0, double tau_penalty_factor, int nlambda, double lambda_factor, double lambda_max, double lambda_0, double C_rho, bool quiet, double eps);
RcppExport SEXP _dcensvm_decentralizedsvm_cpp(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP C_NSEXP, SEXP T_outerSEXP, SEXP c0SEXP, SEXP tau_penalty_factorSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP lambda_0SEXP, SEXP C_rhoSEXP, SEXP quietSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type C_N(C_NSEXP);
    Rcpp::traits::input_parameter< int >::type T_outer(T_outerSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_penalty_factor(tau_penalty_factorSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_0(lambda_0SEXP);
    Rcpp::traits::input_parameter< double >::type C_rho(C_rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(decentralizedsvm_cpp(X, y, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, lambda_0, C_rho, quiet, eps));
    return rcpp_result_gen;
END_RCPP
}
// decentralizedsvm_lambda
Rcpp::List decentralizedsvm_lambda(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec betaT, double h, int type, double C_N, double lambda, int T_outer, double c0, double lambda_0, double tau_penalty_factor, double C_rho, bool quiet, double eps);
RcppExport SEXP _dcensvm_decentralizedsvm_lambda(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP C_NSEXP, SEXP lambdaSEXP, SEXP T_outerSEXP, SEXP c0SEXP, SEXP lambda_0SEXP, SEXP tau_penalty_factorSEXP, SEXP C_rhoSEXP, SEXP quietSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type C_N(C_NSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type T_outer(T_outerSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda_0(lambda_0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_penalty_factor(tau_penalty_factorSEXP);
    Rcpp::traits::input_parameter< double >::type C_rho(C_rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(decentralizedsvm_lambda(X, y, adjacency_matrix, B_init, betaT, h, type, C_N, lambda, T_outer, c0, lambda_0, tau_penalty_factor, C_rho, quiet, eps));
    return rcpp_result_gen;
END_RCPP
}
// decentralizedsvm_cpp_real
Rcpp::List decentralizedsvm_cpp_real(arma::mat& X, arma::vec& y, arma::vec& divisions, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec betaT, double h, int type, double C_N, int T_outer, double c0, double tau_penalty_factor, int nlambda, double lambda_factor, double lambda_max, double lambda_0, double C_rho, bool quiet, double eps);
RcppExport SEXP _dcensvm_decentralizedsvm_cpp_real(SEXP XSEXP, SEXP ySEXP, SEXP divisionsSEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP C_NSEXP, SEXP T_outerSEXP, SEXP c0SEXP, SEXP tau_penalty_factorSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP lambda_0SEXP, SEXP C_rhoSEXP, SEXP quietSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type divisions(divisionsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type C_N(C_NSEXP);
    Rcpp::traits::input_parameter< int >::type T_outer(T_outerSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_penalty_factor(tau_penalty_factorSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_0(lambda_0SEXP);
    Rcpp::traits::input_parameter< double >::type C_rho(C_rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(decentralizedsvm_cpp_real(X, y, divisions, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, lambda_0, C_rho, quiet, eps));
    return rcpp_result_gen;
END_RCPP
}
// pmax_arma
arma::vec pmax_arma(arma::vec x, double bound);
RcppExport SEXP _dcensvm_pmax_arma(SEXP xSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(pmax_arma(x, bound));
    return rcpp_result_gen;
END_RCPP
}
// kernel
arma::mat kernel(arma::mat E, arma::vec h);
RcppExport SEXP _dcensvm_kernel(SEXP ESEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E(ESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel(E, h));
    return rcpp_result_gen;
END_RCPP
}
// calN_j_cpp
arma::uvec calN_j_cpp(int n, int j);
RcppExport SEXP _dcensvm_calN_j_cpp(SEXP nSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(calN_j_cpp(n, j));
    return rcpp_result_gen;
END_RCPP
}
// soft_thresholding_cpp
arma::vec soft_thresholding_cpp(arma::vec x, double t);
RcppExport SEXP _dcensvm_soft_thresholding_cpp(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_thresholding_cpp(x, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dcensvm_SubGD_single_hinge", (DL_FUNC) &_dcensvm_SubGD_single_hinge, 9},
    {"_dcensvm_SubGD_hinge", (DL_FUNC) &_dcensvm_SubGD_hinge, 11},
    {"_dcensvm_deSubGD_single_svm", (DL_FUNC) &_dcensvm_deSubGD_single_svm, 10},
    {"_dcensvm_deSubGD_svm", (DL_FUNC) &_dcensvm_deSubGD_svm, 12},
    {"_dcensvm_deSubGD_single_svm_real", (DL_FUNC) &_dcensvm_deSubGD_single_svm_real, 11},
    {"_dcensvm_deSubGD_svm_real", (DL_FUNC) &_dcensvm_deSubGD_svm_real, 13},
    {"_dcensvm_Phi", (DL_FUNC) &_dcensvm_Phi, 1},
    {"_dcensvm_calL_h_G_prime", (DL_FUNC) &_dcensvm_calL_h_G_prime, 2},
    {"_dcensvm_calL_h_G_double_prime", (DL_FUNC) &_dcensvm_calL_h_G_double_prime, 2},
    {"_dcensvm_grad_hinge_loss", (DL_FUNC) &_dcensvm_grad_hinge_loss, 5},
    {"_dcensvm_L2_HingeLoss", (DL_FUNC) &_dcensvm_L2_HingeLoss, 3},
    {"_dcensvm_calculateAccuracy", (DL_FUNC) &_dcensvm_calculateAccuracy, 2},
    {"_dcensvm_getSampleIndices", (DL_FUNC) &_dcensvm_getSampleIndices, 2},
    {"_dcensvm_decentralizedsvm_cpp", (DL_FUNC) &_dcensvm_decentralizedsvm_cpp, 18},
    {"_dcensvm_decentralizedsvm_lambda", (DL_FUNC) &_dcensvm_decentralizedsvm_lambda, 16},
    {"_dcensvm_decentralizedsvm_cpp_real", (DL_FUNC) &_dcensvm_decentralizedsvm_cpp_real, 19},
    {"_dcensvm_pmax_arma", (DL_FUNC) &_dcensvm_pmax_arma, 2},
    {"_dcensvm_kernel", (DL_FUNC) &_dcensvm_kernel, 2},
    {"_dcensvm_calN_j_cpp", (DL_FUNC) &_dcensvm_calN_j_cpp, 2},
    {"_dcensvm_soft_thresholding_cpp", (DL_FUNC) &_dcensvm_soft_thresholding_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dcensvm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
