# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implements subgradient descent for hinge loss SVM with fixed regularization.
#'
#' This function trains a linear SVM using the hinge loss with L1 regularization.
#' It uses a decaying step size schedule: eta = (a_lambda/(t+1))^{b_lambda}.
#' Convergence is monitored via relative coefficient change between iterations.
#'
#' @param X Design matrix of size N × p (N samples, p features).
#' @param y Response vector of length N (values +1 or -1).
#' @param b_init Initial coefficient vector of length p.
#' @param T Maximum number of iterations.
#' @param a_lambda Step size scaling parameter (default=3.5).
#' @param b_lambda Step size decay exponent (default=0.51).
#' @param lambda L1 regularization parameter (default=1e-2).
#' @param eps Convergence threshold for relative coefficient change (default=1e-4).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing:
#'   - `b`: Final estimated coefficient vector (length p)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative coefficient changes at each iteration
#' @export
SubGD_single_hinge <- function(X, y, b_init, T = 20L, a_lambda = 3.5, b_lambda = 0.51, lambda = 1e-2, eps = 1e-4, quiet = TRUE) {
    .Call(`_dcensvm_SubGD_single_hinge`, X, y, b_init, T, a_lambda, b_lambda, lambda, eps, quiet)
}

#' Implements SVM training with BIC-regularized parameter selection for hinge loss.
#'
#' This function selects optimal lambda via BIC criterion from a regularization path.
#' Lambda values are logarithmically spaced from lambda_max to lambda_max*lambda_factor.
#' For each lambda, trains a model using SubGD_single_hinge and computes BIC as:
#' BIC = hinge_loss + log(N)*sqrt(log(N))*shat, where shat is number of non-zero coefficients.
#' Final model uses lambda minimizing BIC.
#'
#' @param X Design matrix of size N × p (N samples, p features).
#' @param y Response vector of length N (values +1 or -1).
#' @param b_init Initial coefficient vector of length p.
#' @param T Maximum number of iterations per lambda.
#' @param a_lambda Step size scaling parameter (default=3.5).
#' @param b_lambda Step size decay exponent (default=0.51).
#' @param nlambda Number of lambda values in regularization path (default=100).
#' @param lambda_factor Maximum lambda in the regularization path before multiplied scale.
#' @param lambda_max Multiplied scale of all lambda in the regularization path.
#' @param eps Convergence threshold for relative coefficient change (default=1e-4).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing (for optimal lambda):
#'   - `b`: Final estimated coefficient vector (length p)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative coefficient changes at each iteration
#' @export
SubGD_hinge <- function(X, y, b_init, T = 20L, a_lambda = 3.5, b_lambda = 0.51, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, eps = 1e-4, quiet = TRUE) {
    .Call(`_dcensvm_SubGD_hinge`, X, y, b_init, T, a_lambda, b_lambda, nlambda, lambda_factor, lambda_max, eps, quiet)
}

#' Implements decentralized subgradient descent (D-subGD) for SVM with fixed regularization parameter.
#'
#' This function performs decentralized training across multiple nodes defined by an adjacency matrix.
#' It uses a subgradient method with decaying step size (eta = a/(t+1)^b) and L1 regularization.
#' The algorithm converges when relative RMSE change falls below threshold.
#'
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N (values should be +1 or -1).
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param T Maximum number of iterations.
#' @param a Stepsize scaling parameter (default=3.5).
#' @param b Stepsize decay exponent (default=0.51).
#' @param lambda L1 regularization parameter (default=1e-2).
#' @param eps Convergence threshold for relative Frobenius norm change (default=1e-2).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing:
#'   - `B`: Final estimated coefficient matrix (p × m)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative RMSE at each iteration.
#' @export
deSubGD_single_svm <- function(X, y, adjacency_matrix, B_init, T = 20L, a = 3.5, b = 0.51, lambda = 1e-2, eps = 1e-2, quiet = TRUE) {
    .Call(`_dcensvm_deSubGD_single_svm`, X, y, adjacency_matrix, B_init, T, a, b, lambda, eps, quiet)
}

#' Implements decentralized subgradient descent (D-subGD) for SVM with BIC-regularized parameter selection.
#'
#' This function selects optimal lambda via BIC criterion from a regularization path.
#' Lambda values are logarithmically spaced from 1 to lambda_max and then multiplied lambda_factor.
#' For each lambda, trains a model using deSubGD_single_svm_real and computes BIC.
#' Final model uses lambda minimizing BIC = hinge loss + log(N)*sqrt(log(N))*shat.
#'
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N (values should be +1 or -1).
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param T Maximum number of iterations.
#' @param a Step size scaling parameter.
#' @param b Step size decay exponent.
#' @param nlambda Number of lambda values in regularization path (default=100).
#' @param lambda_factor Maximum lambda in the regularization path before multiplied scale.
#' @param lambda_max Multiplied scale of all lambda in the regularization path.
#' @param eps Convergence threshold for relative Frobenius norm change (default=1e-2).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing (for optimal lambda):
#'   - `B`: Final estimated coefficient matrix (p × m)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative RMSE at each iteration
#' @export
deSubGD_svm <- function(X, y, adjacency_matrix, B_init, T = 20L, a = 3.5, b = 0.51, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, eps = 1e-2, quiet = TRUE) {
    .Call(`_dcensvm_deSubGD_svm`, X, y, adjacency_matrix, B_init, T, a, b, nlambda, lambda_factor, lambda_max, eps, quiet)
}

#' Implements decentralized subgradient descent (D-subGD) for SVM with fixed regularization parameter in real-data analysis.
#'
#' This function performs decentralized training across multiple nodes defined by an adjacency matrix.
#' It uses a subgradient method with decaying step size (eta = a/(t+1)^b) and L1 regularization.
#' The algorithm converges when relative RMSE change falls below threshold.
#'
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N (values should be +1 or -1).
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param divisions Real data division (length N, values 1 to m).
#' @param T Maximum number of iterations.
#' @param a Stepsize scaling parameter (default=3.5).
#' @param b Stepsize decay exponent (default=0.51).
#' @param lambda L1 regularization parameter (default=1e-2).
#' @param eps Convergence threshold for relative Frobenius norm change (default=1e-2).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing:
#'   - `B`: Final estimated coefficient matrix (p × m)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative RMSE at each iteration.
#' @export
deSubGD_single_svm_real <- function(X, y, adjacency_matrix, B_init, divisions, T = 20L, a = 3.5, b = 0.51, lambda = 1e-2, eps = 1e-2, quiet = TRUE) {
    .Call(`_dcensvm_deSubGD_single_svm_real`, X, y, adjacency_matrix, B_init, divisions, T, a, b, lambda, eps, quiet)
}

#' Implements decentralized subgradient descent (D-subGD) for SVM with BIC-regularized parameter selection in real-data analysis.
#'
#' This function selects optimal lambda via BIC criterion from a regularization path.
#' Lambda values are logarithmically spaced from 1 to lambda_max and then multiplied lambda_factor.
#' For each lambda, trains a model using deSubGD_single_svm_real and computes BIC.
#' Final model uses lambda minimizing BIC = hinge loss + log(N)*sqrt(log(N))*shat.
#'
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N (values should be +1 or -1).
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param divisions Vector indicating sample assignments to nodes (length N, values 1 to m).
#' @param T Maximum number of iterations.
#' @param a Step size scaling parameter.
#' @param b Step size decay exponent.
#' @param nlambda Number of lambda values in regularization path (default=100).
#' @param lambda_factor Maximum lambda in the regularization path before multiplied scale.
#' @param lambda_max Multiplied scale of all lambda in the regularization path.
#' @param eps Convergence threshold for relative Frobenius norm change (default=1e-2).
#' @param quiet If true, suppresses console output (default=true).
#' @return A list containing (for optimal lambda):
#'   - `B`: Final estimated coefficient matrix (p × m)
#'   - `history`: List containing:
#'        - `errors`: Vector of relative RMSE at each iteration
#' @export
deSubGD_svm_real <- function(X, y, adjacency_matrix, B_init, divisions, T = 20L, a = 3.5, b = 0.51, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, eps = 1e-2, quiet = TRUE) {
    .Call(`_dcensvm_deSubGD_svm_real`, X, y, adjacency_matrix, B_init, divisions, T, a, b, nlambda, lambda_factor, lambda_max, eps, quiet)
}

#' Computes the cumulative distribution function (CDF) of the standard normal distribution.
#'
#' This function uses the complementary error function (`std::erfc`) to compute Φ(x).
#'
#' @param x Input value.
#' @return The value of the CDF at `x`.
Phi <- function(x) {
    .Call(`_dcensvm_Phi`, x)
}

#' Calculates the first derivative of the Gaussian loss function L_h^G(v).
#'
#' @param v Evaluation point.
#' @param h Bandwidth parameter.
#' @return The first derivative of the Gaussian loss function at `v`.
calL_h_G_prime <- function(v, h) {
    .Call(`_dcensvm_calL_h_G_prime`, v, h)
}

#' Calculates the second derivative of the Gaussian loss function L_h^G(v).
#'
#' @param v Evaluation point.
#' @param h Bandwidth parameter.
#' @return The second derivative of the Gaussian loss function at `v`.
calL_h_G_double_prime <- function(v, h) {
    .Call(`_dcensvm_calL_h_G_double_prime`, v, h)
}

#' Computes the gradient of the hinge loss for a specified kernel type.
#'
#' Supported types:
#' - 1: Uniform
#' - 2: Laplacian
#' - 3: Logistic
#' - 4: Gaussian
#' - 5: Epanechnikov
#'
#' @param Y Response vector.
#' @param X Design matrix.
#' @param beta Coefficient vector.
#' @param h Kernel bandwidth.
#' @param type Type of kernel (1–5).
#' @return Gradient of the hinge loss as an Armadillo vector.
#' @export
grad_hinge_loss <- function(Y, X, beta, h, type) {
    .Call(`_dcensvm_grad_hinge_loss`, Y, X, beta, h, type)
}

#' Computes the L2-regularized hinge loss for a specific kernel type.
#'
#' Supported types:
#' - 1: Uniform
#' - 2: Laplacian
#' - 3: Logistic
#' - 4: Gaussian
#' - 5: Epanechnikov
#'
#' @param v Evaluation point.
#' @param h Kernel bandwidth.
#' @param type Type of kernel (1–5).
#' @return Value of the L2-regularized hinge loss at `v`.
#' @export
L2_HingeLoss <- function(v, h, type) {
    .Call(`_dcensvm_L2_HingeLoss`, v, h, type)
}

#' Calculates classification accuracy by comparing predicted labels with true labels.
#'
#' @param y True labels.
#' @param y_pred Predicted values.
#' @return Classification accuracy as a percentage.
#' @export
calculateAccuracy <- function(y, y_pred) {
    .Call(`_dcensvm_calculateAccuracy`, y, y_pred)
}

#' Finds indices of samples that belong to a specific partition.
#'
#' @param divisions Vector indicating which partition each sample belongs to.
#' @param division Partition number to extract.
#' @return Armadillo unsigned integer vector containing indices of samples in the specified partition.
#' @export
getSampleIndices <- function(divisions, division) {
    .Call(`_dcensvm_getSampleIndices`, divisions, division)
}

#' Implements a decentralized SVM algorithm using ADMM optimization.
#'
#' Supports various kernel types and performs feature selection using soft thresholding.
#' Lambda values are logarithmically spaced from 1 to lambda_max and then multiplied lambda_factor.
#' Also calculates accuracy, BIC, and other performance metrics.
#'
#' @param X Design matrix of size N × p.
#' @param y Response vector of length N.
#' @param adjacency_matrix Matrix defining communication links between nodes.
#' @param B_init Initial coefficient matrix.
#' @param betaT True coefficient vector used for error calculation (ground truth).
#' @param h Kernel bandwidth.
#' @param type Kernel type (1–5).
#' @param C_N Regularization constant for BIC.
#' @param T_outer Number of iterations.
#' @param c0 Constant for step-size control (not used here but kept for consistency).
#' @param lambda_0 Regularization term of L2 penalty.
#' @param nlambda Number of regularization path points.
#' @param lambda_factor Maximum lambda in the regularization path before multiplied scale.
#' @param lambda_max Multiplied scale of all lambda in the regularization path.
#' @param tau_penalty_factor A penalty parameter in the augmented Lagrangian.
#' @param C_rho Scaling factor for rho_l update.
#' @param quiet Whether to suppress output messages.
#' @param eps Convergence tolerance (not currently used in stopping criterion).
#' @return A list containing:
#' - `B`: Final estimated coefficients (p × m matrix).
#' - `history`: List containing:
#'   - `errors_outer`: Frobenius norm errors over iterations.
#'   - `loss_error`: Hinge loss over iterations.
#'   - `shat_array`: Estimated sparsity (number of non-zero coefficients) over iterations.
#'   - `accuracy`: Classification accuracy over iterations.
#'  - `bic_mat`: BIC under different lambda.
#' @export
decentralizedsvm_cpp <- function(X, y, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer = 10L, c0 = 0.1, tau_penalty_factor = 1 / 6, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, lambda_0 = 0.5, C_rho = 1.01, quiet = TRUE, eps = 1e-2) {
    .Call(`_dcensvm_decentralizedsvm_cpp`, X, y, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, lambda_0, C_rho, quiet, eps)
}

#' Implements a decentralized penalized convoluted support vector machine (deCSVM) with fixed regularization parameter lambda using ADMM optimization.
#'
#' This function performs decentralized training across multiple nodes defined by the adjacency matrix.
#'
#' It supports various kernel types for hinge loss computation and applies soft thresholding for feature selection.
#' Unlike `decentralizedsvm_cpp`, this version uses a fixed regularization parameter `lambda`.
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N.
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param betaT True coefficient vector used for error calculation (ground truth).
#' @param h Kernel bandwidth.
#' @param type Type of kernel function to use (1: Uniform, 2: Laplacian, 3: Logistic, 4: Gaussian, 5: Epanechnikov).
#' @param C_N Regularization constant used in BIC calculation.
#' @param lambda Fixed L1 regularization parameter.
#' @param T_outer Maximum number of iterations.
#' @param c0 Constant for step-size control (not used here but kept for consistency).
#' @param lambda_0 Regularization term of L2 penalty.
#' @param tau_penalty_factor A penalty parameter in the augmented Lagrangian.
#' @param C_rho Scaling factor for rho_l update.
#' @param quiet If true, suppresses console output.
#' @param eps Convergence tolerance (not currently used in stopping criterion).
#' @return A list containing:
#' - `B`: Final estimated coefficients (p × m matrix).
#' - `history`: List containing:
#'   - `errors_outer`: Frobenius norm errors over iterations.
#'   - `loss_error`: Hinge loss over iterations.
#'   - `shat_array`: Estimated sparsity (number of non-zero coefficients) over iterations.
#'   - `accuracy`: Classification accuracy over iterations.
#' @export
decentralizedsvm_lambda <- function(X, y, adjacency_matrix, B_init, betaT, h, type, C_N, lambda, T_outer = 10L, c0 = 0.1, lambda_0 = 0, tau_penalty_factor = 1 / 6, C_rho = 1.01, quiet = TRUE, eps = 1e-2) {
    .Call(`_dcensvm_decentralizedsvm_lambda`, X, y, adjacency_matrix, B_init, betaT, h, type, C_N, lambda, T_outer, c0, lambda_0, tau_penalty_factor, C_rho, quiet, eps)
}

#' Implements a decentralized penalized convoluted support vector machine (deCSVM) for real data analysis using ADMM optimization.
#'
#' This function performs decentralized training across multiple nodes defined by the adjacency matrix of real data.
#' It supports various kernel types for hinge loss computation and applies soft thresholding for feature selection.
#'
#' @param X Design matrix of size N × p (N total samples, p features).
#' @param y Response vector of length N.
#' @param divisions Real data divisions.
#' @param adjacency_matrix Matrix defining communication links between nodes (m × m).
#' @param B_init Initial coefficient matrix of size p × m (one coefficient vector per node).
#' @param betaT True coefficient vector used for error calculation (ground truth).
#' @param h Kernel bandwidth.
#' @param type Type of kernel function to use (1: Uniform, 2: Laplacian, 3: Logistic, 4: Gaussian, 5: Epanechnikov).
#' @param C_N Regularization constant used in BIC calculation.
#' @param lambda Fixed L1 regularization parameter.
#' @param T_outer Maximum number of iterations.
#' @param c0 Constant for step-size control (not used here but kept for consistency).
#' @param lambda_0 Regularization term of L2 penalty.
#' @param nlambda Number of regularization path points.
#' @param lambda_factor Maximum lambda in the regularization path before multiplied scale.
#' @param lambda_max Multiplied Scale of all lambda in the regularization path.
#' @param tau_penalty_factor Penalty factor for consensus term based on spectral norm.
#' @param C_rho Scaling factor for rho_l update.
#' @param quiet If true, suppresses console output.
#' @param eps Convergence tolerance (not currently used in stopping criterion).
#' @return A list containing:
#' - `B`: Final estimated coefficients (p × m matrix).
#' @export
decentralizedsvm_cpp_real <- function(X, y, divisions, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer = 10L, c0 = 0.1, tau_penalty_factor = 1 / 6, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, lambda_0 = 0.5, C_rho = 1.01, quiet = TRUE, eps = 1e-2) {
    .Call(`_dcensvm_decentralizedsvm_cpp_real`, X, y, divisions, adjacency_matrix, B_init, betaT, h, type, C_N, T_outer, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, lambda_0, C_rho, quiet, eps)
}

#' RcppArmadillo implementation of the R pmax()
#' function
#'
#' @title RcppArmadillo implemenation of the r pmax function
#' @param x the (aramdillo) vector
#' @param bound the (double) bound
#' @export
pmax_arma <- function(x, bound) {
    .Call(`_dcensvm_pmax_arma`, x, bound)
}

#' Computes a kernel function for density estimation.
#'
#' This kernel satisfies ∫K(u)du=1, ∫uK(u)du=0, and ∫u^2K(u)du=0.
#' The kernel is defined as: K(u) = [-315u^6 + 735u^4 - 525u^2 + 105]/64 for |u|<1, 0 otherwise.
#'
#' @param E Matrix of input values where kernel should be evaluated.
#' @param h Bandwidth vector controlling the kernel width.
#' @return Matrix of kernel density estimates scaled by bandwidth.
kernel <- function(E, h) {
    .Call(`_dcensvm_kernel`, E, h)
}

#' Generates consecutive indices for block j in a partitioned dataset.
#'
#' This function creates index sequences for data partitioned into equal-sized blocks.
#'
#' @param n Size of each data block (number of samples per partition).
#' @param j Block index (0-based).
#' @return Vector of consecutive indices for the j-th block: [n*j, n*(j+1)-1].
#' @export
calN_j_cpp <- function(n, j) {
    .Call(`_dcensvm_calN_j_cpp`, n, j)
}

#' Applies soft thresholding operator for L1 regularization.
#'
#' This implements the proximal operator for L1 norm: S_t(x) = sign(x)*max(|x|-t, 0).
#'
#' @param x Input vector of coefficients.
#' @param t Threshold parameter (controls sparsity level).
#' @return Thresholded vector where values within [-t, t] are set to zero.
soft_thresholding_cpp <- function(x, t) {
    .Call(`_dcensvm_soft_thresholding_cpp`, x, t)
}

